 /*  var newWeather = new weatherDesc({Type:'NA' , WeatherDescription: 'Not available'});
    newWeather.save();*/
 /*   var newWeather2 = new weatherDesc({Type:'0' , WeatherDescription: 'Clear night'});
    newWeather2.save();
    var newWeather3 = new weatherDesc({Type:'1' , WeatherDescription: 'Sunny day'});
    newWeather3.save();
    var newWeather4 = new weatherDesc({Type:'2' , WeatherDescription: 'Partly cloudy (night)'});
    newWeather4.save();
    var newWeather5 = new weatherDesc({Type:'3' , WeatherDescription: 'Partly cloudy (day)'});
    newWeather5.save();
    var newWeather6 = new weatherDesc({Type:'4' , WeatherDescription: 'Not used'});
    newWeather6.save();
    var newWeather7 = new weatherDesc({Type:'5' , WeatherDescription: 'Mist'});
    newWeather7.save();
    var newWeather8 = new weatherDesc({Type:'6' , WeatherDescription: 'Fog'});
    newWeather8.save();
    var newWeather9 = new weatherDesc({Type:'7' , WeatherDescription: 'Cloudy'});
    newWeather9.save();
    var newWeather10 = new weatherDesc({Type:'8' , WeatherDescription: 'Overcast'});
    newWeather10.save();
    var newWeather11 = new weatherDesc({Type:'9' , WeatherDescription: 'Light rain shower (night)'});
    newWeather11.save();
    var newWeather12 = new weatherDesc({Type:'10' , WeatherDescription: 'Light rain shower (day)'});
    newWeather12.save();
    var newWeather13 = new weatherDesc({Type:'11' , WeatherDescription: 'Drizzle'});
    newWeather13.save();
    var newWeather14 = new weatherDesc({Type:'12' , WeatherDescription: 'Light rain'});
    newWeather14.save();
    var newWeather15 = new weatherDesc({Type:'13' , WeatherDescription: 'Heavy rain shower (night)'});
    newWeather15.save();
    var newWeather16 = new weatherDesc({Type:'14' , WeatherDescription: 'Heavy rain shower (day)'});
    newWeather16.save();
    var newWeather17 = new weatherDesc({Type:'15' , WeatherDescription: 'Heavy rain'});
    newWeather17.save();
    var newWeather18 = new weatherDesc({Type:'16' , WeatherDescription: 'Sleet shower (night)'});
    newWeather18.save();
    var newWeather19 = new weatherDesc({Type:'17' , WeatherDescription: 'Sleet shower (day)'});
    newWeather19.save();
    var newWeather20 = new weatherDesc({Type:'18' , WeatherDescription: 'Sleet'});
    newWeather20.save();
    var newWeather21 = new weatherDesc({Type:'19' , WeatherDescription: 'Hail shower (night)'});
    newWeather21.save();
    var newWeather22 = new weatherDesc({Type:'20' , WeatherDescription: 'Hail shower (day)'});
    newWeather22.save();
    var newWeather23 = new weatherDesc({Type:'21' , WeatherDescription: 'Hail'});
    newWeather23.save();
    var newWeather24 = new weatherDesc({Type:'22' , WeatherDescription: 'Light snow shower (night)'});
    newWeather24.save();
   var  newWeather25 = new weatherDesc({Type:'23' , WeatherDescription: 'Light snow shower (day)'});
    newWeather25.save();
    var newWeather26 = new weatherDesc({Type:'24' , WeatherDescription: 'Light snow'});
    newWeather26.save();
    var newWeather27 = new weatherDesc({Type:'25' , WeatherDescription: 'Heavy snow shower (night)'});
    newWeather27.save();
    var newWeather28 = new weatherDesc({Type:'26' , WeatherDescription: 'Heavy snow shower (day)'});
    newWeather28.save();
    var newWeather29 = new weatherDesc({Type:'27' , WeatherDescription: 'Heavy snow'});
    newWeather29.save();
    var newWeather30 = new weatherDesc({Type:'28' , WeatherDescription: 'Thunder shower (night)'});
    newWeather30.save();
    var newWeather31 = new weatherDesc({Type:'29' , WeatherDescription: 'Thunder shower (day)'});
    newWeather31.save();
    var newWeather32 = new weatherDesc({Type:'30' , WeatherDescription: 'Thunder'});
    newWeather32.save();
*/